name: C++ Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      QT_EMAIL: ${{ secrets.QT_ACCOUNT_EMAIL }}
      QT_PASSWORD: ${{ secrets.QT_ACCOUNT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake

      - name: Install Qt 6.9.0 (with qtimageformats) via aqt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.9.0'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qtimageformats'
          install-deps: true
          cache: true
          set-env: true

      - name: Configure project (Release + Ninja)
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure
